### ISSUE TITLE
Conflicts with dokuwiki plugin tags

### ISSUE THREAD

**Issue by dryoo** [cosmocode/dokuwiki-plugin-top#9]
![-1](https://cloud.githubusercontent.com/assets/799405/16439701/e7ffd1b2-3df5-11e6-838f-c8c78fa72e0e.jpg)
![-2](https://cloud.githubusercontent.com/assets/799405/16439703/ea2b1e74-3df5-11e6-84ad-c5909b0af11e.jpg)
![-3](https://cloud.githubusercontent.com/assets/799405/16439704/ef4d9620-3df5-11e6-9be1-1b39afb01814.jpg)

When top is actived, tag plugin does not work correctly

You can see here!

[http://openwiki.kr/test](url)

is this problem of the cache?

**Comment by clemenskuehn** [comment]
Same problem: when plugin:top is activated, dokuwiki recognizes 
{{topic>....}}
as 
{{top...}}
I don't know what the next error is because I did not install plugin:sqlite and just deactivated plugin:top since I didn't use it anyways. 
But this almost seems like a general error in matching the keywords of plugins that are substrings of other keywords.
